# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9602796a52bcddb24b927609a9b491b0dd74242e0594df8c8b5651e485cea6dfb6955b57799f00ad92908ebfd75a61ec437491011cc8b9c1d87ee9d1fb5c20db

test:
  secret_key_base: 3f116938abba3a26e28fe2dd413c6544b045ac07e1cf62e5034743b6ac19577d9112765cccb8fbc58750b54833c7ebf47562a42545ea00c3338b0f883455d63f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
